# Load DSL and Setup Up Stages
require 'capistrano/setup'
require 'capistrano/deploy'

require 'capistrano/rails'
require 'capistrano/bundler'
require 'capistrano/rvm'
require 'capistrano/puma'
install_plugin Capistrano::Puma

require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git

# require 'capistrano/sidekiq' use it in future
require 'capistrano/sidekiq'
# install_plugin Capistrano::Sidekiq  # Default sidekiq tasks

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
