source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'

# ActiveAdmin
gem 'activeadmin'
# Plus integrations with:
gem 'cancancan'
gem 'devise'
gem 'draper'
gem 'pundit'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0'

gem 'nokogiri'

# Postgres
gem 'activerecord-pg_enum'
gem 'pg'

# Use Puma as the app server
gem 'puma', '~> 5.5'

# Sentry
gem 'sentry-ruby'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

# Twitter
gem 'oauth'
gem 'twitter'

# Http requests
gem 'httparty'

# RSS -> using my branch since... there is a bug that does not let me parse the RSS directly from AnchorFM
# gem 'rss', git: 'git@github.com:jmsalcido/rss.git', branch: 'js/itunes-duration-integer' # => Not working on 2.6.0 build
# Using Simple RSS
# gem 'simple-rss' # -> not reading Itunes values
gem 'feedjira' # combo with httparty. see docs.

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap'

# Jobs
# Sidekiq
gem 'sidekiq'
gem 'sidekiq-cron'

# Ruby progressbar master race.
gem 'ruby-progressbar'

# CORS middleware.
gem 'rack-cors'

# Testing and Debugging in general
group :test, :development do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'rspec-rails', '~> 5.1.2'
end

# Testing
group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'webdrivers'

  gem 'factory_bot'
  gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'
  gem 'webmock'
end

# Making life easier for developer
group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen'
  gem 'web-console'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'awesome_print'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rubocop', require: false
  gem 'rubocop-faker', require: false
  gem 'spring'
  gem 'spring-watcher-listen'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
