source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# ActiveAdmin
gem 'activeadmin'
# Plus integrations with:
gem 'cancancan'
gem 'devise'
gem 'draper'
gem 'pundit'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'

# Postgres
gem 'pg'

# Use Puma as the app server
gem 'puma', '~> 5.6'

# Sentry
gem 'sentry-ruby'

# Javascript Runtime
gem 'therubyracer'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Twitter
gem 'oauth'
gem 'twitter'

# Http requests
gem 'httparty'

# RSS -> using my branch since... there is a bug that does not let me parse the RSS directly from AnchorFM
# gem 'rss', git: 'git@github.com:jmsalcido/rss.git', branch: 'js/itunes-duration-integer' # => Not working on 2.6.0 build
# Using Simple RSS
# gem 'simple-rss' # -> not reading Itunes values
gem 'feedjira' # combo with httparty. see docs.

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Jobs
# Sidekiq
gem 'sidekiq', '~> 5.2', '>= 5.2.7'
gem 'sidekiq-cron'

# Ruby progressbar master race.
gem 'ruby-progressbar'

# CORS middleware.
gem 'rack-cors'

# Testing and Debugging in general
group :test, :development do
  gem 'rspec-rails', '~> 4.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'

  gem 'factory_bot'
  gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'
  gem 'webmock'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

# Making life easier for developer
group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'awesome_print'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rubocop', require: false
  gem 'rubocop-faker', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'dotenv-rails', groups: %i[development test]

# Capistrano and deployment
group :development do
  gem 'capistrano', '3.15', require: false
  gem 'capistrano3-puma', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-rails', require: false
  gem 'capistrano-rvm', require: false
  gem 'capistrano-sidekiq'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
